on: 
  workflow_dispatch:
  pull_request:

jobs:
  example_comment_pr:
    permissions: write-all
    runs-on: ubuntu-latest
    name: An example job to comment a PR
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      
      - name: write-to-pr-new
        id: write-to-pr-new
        uses: ./.github/write_to_commit/

      - name: Comment PR
        uses: thollander/actions-comment-pull-request@v2
        with:
          message: |
            Hello world ! :wave:
              